version: 0.2

phases:
  pre_build:
    commands:
      - echo Preparing to upload the image...
  build:
    commands:
      - echo Uploading the image to S3...
      - aws s3 cp "path/to/your/stavir services.png" s3://my-bucket-cicd/
  post_build:
    commands:
      - echo Invalidating CloudFront cache...
      - aws cloudfront create-invalidation --distribution-id E1W6B4DVJ2JF3R --paths "/*"

artifacts:
  files:
    - '**/*'
