version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing AWS CLI"
      - pip install awscli
  pre_build:
    commands:
      - echo "Pre-build phase started at `date`"
  build:
    commands:
      - echo "Deploying stavir services.png to S3 bucket my-bucket-cicd"
      - aws s3 cp "stavir services.png" s3://my-bucket-cicd/  # Upload the specific PNG file
      - echo "Triggering CloudFront invalidation"
      - aws cloudfront create-invalidation --distribution-id E1W6B4DVJ2JF3R --paths "/stavir%20services.png"  # Invalidate the specific file
  post_build:
    commands:
      - echo "Build completed at `date`"

artifacts:
  files:
    - "stavir services.png"  # Specify the PNG file as an artifact if needed

cache:
  paths:
    - './node_modules/**/*'
